language: scala

scala: 2.11.7

jdk: oraclejdk8

env:
  - CODACY_PROJECT_TOKEN=7bb368f5bdff4cd8b8fcc18f5192397d

script: ./build.sh

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt/boot

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/648ac1bd320fb1242e3e
